apiVersion: apps/v1
kind: Deployment
metadata:
  name: river-api
  labels:
    app: river-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: river-api
  template:
    metadata:
      labels:
        app: river-api
    spec:
      imagePullSecrets:
      - name: acr-credentials
      containers:
      - name: river-api
        image: river.azurecr.io/river-rest-api:v3
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: '/mnt/azure'
          name: river-disk
        - mountPath: '/app/appsettings.json'
          subPath: 'api/appsettings.json'
          name: river-disk
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
      volumes:
      - name: river-disk
        persistentVolumeClaim:
          claimName: river-disk
---
apiVersion: v1
kind: Service
metadata:
  name: river-api
spec:
  selector:
    app: river-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: river-disk
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/river-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: river-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi